### ISSUE TITLE
ERROR while Import odoo8

### ISSUE THREAD

**Issue by bambid** [OCA/bank-statement-import#150]
Hello
Ive Installed the odoo8 on a synology DS. i have installed the Module and if i press the Import button i get this response:
Field account.bank.statement.import.hide_journal_field is accessed before being computed.

The Logfile is:
```
2018-02-28 21:09:18,744 11680 ERROR Zoggeli openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 516, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 279, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 732, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 375, in response_wrap
    response = f(*args, **kw)
  File "/var/packages/Odoo8/target/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/var/packages/Odoo8/target/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/models.py", line 1331, in default_get
    value = record[name]
  File "/usr/local/lib/python2.7/site-packages/openerp/models.py", line 5441, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/local/lib/python2.7/site-packages/openerp/fields.py", line 717, in __get__
    return record._cache[self]
  File "/usr/local/lib/python2.7/site-packages/openerp/models.py", line 5775, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/local/lib/python2.7/site-packages/openerp/fields.py", line 55, in get
    raise self.exception
Warning: Field account.bank.statement.import.hide_journal_field is accessed before being computed.
```
so what can i do? did i forget somthing?

kind regards
bambid

**Comment by bambid** [comment]
Ive uninstalled the module and reinstalled the module and now i get an other error:
`Error while importing module 'account_bank_statement_import': '"ValidateError\nField(s) `arch` failed against a constraint: Invalid view definition\n\nError details:\nField `module_base_bank_account_number_unique` does not exist\n\nError context:\nView `account.config.settings form`\n[view_id: 566, xml_id: n/a, model: account.config.settings, parent_id: 495]" while parsing /tmp/tmpGe7W5H/account_bank_statement_import/views/account_config_settings.xml:4, near\n<record id="view_account_config_settings" model="ir.ui.view">\n <field name="model">account.config.settings</field>\n <field name="inherit_id" ref="account.view_account_config_settings"/>\n <field name="arch" type="xml">\n <xpath expr="." position="inside">\n <separator name="account_bank_statement_import" string="Bank statement import"/>\n <group>\n <field name="module_base_bank_account_number_unique"/>\n </group>\n </xpath>\n </field>\n </record>' Error while importing module 'account_bank_statement_import_mt940_base': "(u'Error !', u'Unmet module dependencies: account_bank_statement_import')"`

is there a problem with the installation of the odoo?

kind regards

`

**Comment by NL66278** [comment]
@bambid It might be that you have to do a full update of your database. That is, update the base module. This will first reload all available modules with the right dependency tree and then update all installed modules.
