### ISSUE TITLE
[11.0] strptime() argument 1 must be str, not datetime.date

### ISSUE THREAD

**Issue by Noirvent** [OCA/bank-statement-import#247]
Hello,
I'm trying to use your modules for importing paypal monthly statements as well as bank statements (camt.053) via [this](https://github.com/OCA/l10n-switzerland/tree/11.0/l10n_ch_bank_statement_import_postfinance) which use your as dependancy.

For both statements (paypal and postfinance), I get the same python error, which is:
**`TypeError: strptime() argument 1 must be str, not datetime.date`**

Stacktrace:
```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/srv/odoo/odoo11-itopie/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/odoo/odoo11-itopie/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/srv/odoo/odoo11-itopie/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/srv/odoo/odoo11-itopie/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/srv/odoo/odoo11-itopie/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/odoo/odoo11-itopie/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/odoo/odoo11-itopie/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/srv/odoo/odoo11-itopie/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/srv/odoo/odoo11-itopie/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/srv/odoo/odoo11-itopie/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/srv/odoo/odoo11-itopie/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/srv/odoo/odoo11-itopie/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/srv/odoo/odoo11-itopie/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/srv/odoo/odoo11-itopie/addons/account_bank_statement_import/account_bank_statement_import.py", line 49, in import_file
    stmts_vals = self._complete_stmts_vals(stmts_vals, journal, account_number)
  File "/srv/odoo/odoo11-itopie/addons-oca-enabled/account_bank_statement_import_split/models/account_bank_statement_import.py", line 77, in _complete_stmts_vals
    statement_date_until,
  File "/srv/odoo/odoo11-itopie/addons-oca-enabled/account_bank_statement_import_split/models/account_bank_statement_import.py", line 152, in _get_statement_name
    ir_sequence_date=self._get_statement_date(date_since, date_until)
  File "/srv/odoo/odoo11-itopie/odoo/addons/base/ir/ir_sequence.py", line 263, in next_by_id
    return self._next()
  File "/srv/odoo/odoo11-itopie/odoo/addons/base/ir/ir_sequence.py", line 257, in _next
    return seq_date.with_context(ir_sequence_date_range=seq_date.date_from)._next()
  File "/srv/odoo/odoo11-itopie/odoo/addons/base/ir/ir_sequence.py", line 352, in _next
    return self.sequence_id.get_next_char(number_next)
  File "/srv/odoo/odoo11-itopie/odoo/addons/base/ir/ir_sequence.py", line 224, in get_next_char
    interpolated_prefix, interpolated_suffix = self._get_prefix_suffix()
  File "/srv/odoo/odoo11-itopie/odoo/addons/base/ir/ir_sequence.py", line 215, in _get_prefix_suffix
    d = _interpolation_dict()
  File "/srv/odoo/odoo11-itopie/odoo/addons/base/ir/ir_sequence.py", line 199, in _interpolation_dict
    effective_date = datetime.strptime(self._context.get('ir_sequence_date'), '%Y-%m-%d')
TypeError: strptime() argument 1 must be str, not datetime.date
```

Odoo Version: 11.0
Python version: 3.5.3
OS: Debian Stretch (9.6)

Could you help me ?

Thanks in advance

**Comment by Noirvent** [comment]
My issue is still here. Could anyone give me hints as to how resolve this ?

**Comment by alexey-pelykh** [comment]
The log you've provided suggests that you have `account_bank_statement_import_split` installed, but that's a v12, not v11 module, and the issue is marked as the one in v11. Is it reproducible on Runbot?

**Comment by Noirvent** [comment]
> but that's a v12, not v11 module

omg indeed you were right. I was on the v12 branch. I'm ashamed to not have seen this sooner.
I've uninstalled all modules, checkout the 11.0 branch and reinstalled them, it works fine now.
Thank you very much !
