### ISSUE TITLE
[12.0][Error] account_bank_statement_import_txt_xlsx 

### ISSUE THREAD

**Issue by Bilbonet** [OCA/bank-statement-import#261]
It doesn't work for me. I have tried it in Runbot and doesn't work too. I tried many configurations and none of them have worked.

**For example with this configuration map:**
   Thousands separator = none
   Decimals separator = comma (,)
   Encoding = UTF-8
   Separated by = semicolon (;)

**I tried to import a CSV file with this content::**
Date;Name;Amount
29/02/2020;Partner1;-2,41
29/02/2020;Partner2;-1,21

**The answer was this:**

Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/OCB-12.0/addons/account_bank_statement_import/account_bank_statement_import.py", line 37, in import_file
    currency_code, account_number, stmts_vals = self.with_context(active_id=self.ids[0])._parse_file(base64.b64decode(self.data_file))
  File "/home/odoo/build/OCA/bank-statement-import/account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal.py", line 214, in _parse_file
    data_file)
  File "/home/odoo/build/OCA/bank-statement-import/account_bank_statement_import_txt_xlsx/wizards/account_bank_statement_import_txt.py", line 255, in _parse_file
    raw_lines = self._parse_txt_file(data_file)
  File "/home/odoo/build/OCA/bank-statement-import/account_bank_statement_import_txt_xlsx/wizards/account_bank_statement_import_txt.py", line 140, in _parse_txt_file
    raw_lines.append(self._convert_txt_line_to_dict(idx, line))
  File "/home/odoo/build/OCA/bank-statement-import/account_bank_statement_import_txt_xlsx/wizards/account_bank_statement_import_txt.py", line 115, in _convert_txt_line_to_dict
    _logger.debug('Trying to convert %s to float' % rline[field])
KeyError: 'amount_currency'

**Comment by alexey-pelykh** [comment]
Please give it a try with this pr #264

**Comment by alexey-pelykh** [comment]
As per comment from @Bilbonet, this issue is addressed via #264
