### ISSUE TITLE
[11] [12] Error when Paypal statement is imported

### ISSUE THREAD

**Issue by ghost** [OCA/bank-statement-import#268]
Hello,
When I t've tried to import Paypal statement I get this traceback:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo12-pre/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12-pre/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12-pre/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12-pre/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12-pre/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12-pre/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12-pre/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12-pre/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12-pre/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12-pre/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12-pre/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12-pre/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12-pre/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12-pre/odoo/addons/account_bank_statement_import/account_bank_statement_import.py", line 37, in import_file
    currency_code, account_number, stmts_vals = self.with_context(active_id=self.ids[0])._parse_file(base64.b64decode(self.data_file))
  File "/opt/odoo12-pre/OCA/bank-statement-import/account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal.py", line 216, in _parse_file
    raw_lines = self._parse_paypal_file(data_file)
  File "/opt/odoo12-pre/OCA/bank-statement-import/account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal.py", line 121, in _parse_paypal_file
    raw_lines.append(self._convert_paypal_line_to_dict(idx, line))
  File "/opt/odoo12-pre/OCA/bank-statement-import/account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal.py", line 87, in _convert_paypal_line_to_dict
    paypal_map = self.mapped('paypal_map_id.map_line_ids')[item]
  File "/opt/odoo12-pre/odoo/odoo/models.py", line 5138, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range

It happened to me on V11 and V12 with different statements.

**Comment by alexey-pelykh** [comment]
Please try to reproduce the error on runbot, and from the log it's clearly older version of plugin that there's right now

**Comment by ghost** [comment]
Hello,
I have seen that version is diferent on runbot. I have tried to import the statement but I can't. Can you help me? I attach a video.
https://drive.google.com/file/d/1iqpZZEtZ8p1XxVLGkxMV5i3PTyKTrlRz/view
Thanks

**Comment by alexey-pelykh** [comment]
Are you using file as-is downloaded from PayPal?

**Comment by gelo-landoo** [comment]
Hello,
Yes, I have downloaded one and I haven't modified before.
I have opened it during this video, not before.
https://drive.google.com/file/d/1-5AhzLSChqt8X1fX_xHpX43aRGJ4g5iY/view
Thanks.

**Comment by alexey-pelykh** [comment]
In order to debug it locally, would it be possible to share that file? (privately)

**Comment by gelo-landoo** [comment]
Sure. How can I send you?
Thanks

**Comment by ghost** [comment]
Hi @alexey-pelykh .
I have sent you the file by mail.
Thanks.

**Comment by alexey-pelykh** [comment]
@gelo-landoo thanks, I'll look into it soon

**Comment by alexey-pelykh** [comment]
Should be fixed in #270
