### ISSUE TITLE
[11.0][Error] Update all

### ISSUE THREAD

**Issue by matteoopenf** [OCA/bank-statement-import#314]
Hi There,

today I try to do an update all of my env and I obtain the following:

2020-07-30 15:07:55,514 1 ERROR customer_db OpenUpgrade: not enough arguments for format string
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/community_addons/bundles/bank-statement-import/account_bank_statement_import_paypal/migrations/11.0.3.0.0/post-migration.py", line 102, in migrate
    """
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade.py", line 927, in logged_query
    logger.debug('Running %s', query % args)
TypeError: not enough arguments for format string
2020-07-30 15:07:55,517 1 WARNING customer_db odoo.modules.loading: Transient module states were reset
2020-07-30 15:07:55,517 1 ERROR customer_db odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 188, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/odoo/odoo/odoo/modules/migration.py", line 190, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/community_addons/bundles/bank-statement-import/account_bank_statement_import_paypal/migrations/11.0.3.0.0/post-migration.py", line 102, in migrate
    """
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade.py", line 927, in logged_query
    logger.debug('Running %s', query % args)
TypeError: not enough arguments for format string
2020-07-30 15:07:55,518 1 CRITICAL customer_db odoo.service.server: Failed to initialize database `customer_db`.
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/service/server.py", line 1043, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 188, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/odoo/odoo/odoo/modules/migration.py", line 190, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/community_addons/bundles/bank-statement-import/account_bank_statement_import_paypal/migrations/11.0.3.0.0/post-migration.py", line 102, in migrate
    """
  File "/usr/local/lib/python3.7/dist-packages/openupgradelib/openupgrade.py", line 927, in logged_query
    logger.debug('Running %s', query % args)
TypeError: not enough arguments for format string
2020-07-30 15:07:55,518 1 INFO customer_db odoo.service.server: Initiating shutdown
2020-07-30 15:07:55,518 1 INFO customer_db odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

I see that  account_bank_statement_import_paypal is updated recently.
I should to do something before do the upgrade?

Many Thanks for the help

**Comment by pedrobaeza** [comment]
Using OpenUpgrade? Unless you specify more details, this seems a bad use of things...
