### ISSUE TITLE
[12.0] [Error]: account_bank_statement_import_online_qonto tracback when pulling statements

### ISSUE THREAD

**Issue by njeudy** [OCA/bank-statement-import#353]
When I try to run cron or pull wizard with my qonto account I get this error ..

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/account_bank_statement_import_online/wizards/online_bank_statement_pull_wizard.py", line 36, in action_pull
    self.date_until
  File "/opt/odoo/auto/addons/account_bank_statement_import_online/models/online_bank_statement_provider.py", line 213, in _pull
    statement_date_until,
  File "/opt/odoo/auto/addons/account_bank_statement_import_online_qonto/models/online_bank_statement_provider_qonto.py", line 40, in _get_statement_date
    return date_since.astimezone(pytz.timezone('Europe/Paris')).date()
ValueError: astimezone() cannot be applied to a naive datetime

**Comment by njeudy** [comment]
@fmdl Any idea on this ?

**Comment by fmdl** [comment]
nop, can you make a print of date_since ?

**Comment by alexey-pelykh** [comment]
Please also double check if most recent versions of corresponding modules are installed

**Comment by njeudy** [comment]
It's ok now.
