### ISSUE TITLE
test of ofx imports fails, resulting in all bank import buildouts to turn red

### ISSUE THREAD

**Issue by NL66278** [OCA/bank-statement-import#76]
test of ofx imports fails, resulting in all bank import buildouts to turn red

The problem seems to be that the version of ofx used in buildout no longer recognizes an balance attribute on ofx.statement.

2016-10-20 10:14:09,554 7004 INFO openerp_test openerp.modules.module: module account_bank_statement_import_ofx: creating or updating database tables

2016-10-20 10:14:09,568 7004 INFO openerp_test openerp.modules.loading: loading account_bank_statement_import_ofx/demo/demo_data.xml

2016-10-20 10:14:09,626 7004 INFO openerp_test openerp.modules.module: openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement running tests.

2016-10-20 10:14:09,627 7004 INFO openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: test_ofx_file_import (openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement.TestOfxFile)

2016-10-20 10:14:09,658 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: ERROR

2016-10-20 10:14:09,658 7004 INFO openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: ======================================================================

2016-10-20 10:14:09,658 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: ERROR: test_ofx_file_import (openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement.TestOfxFile)

2016-10-20 10:14:09,659 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: Traceback (most recent call last):

2016-10-20 10:14:09,659 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `   File "/home/travis/build/NL66278/bank-statement-import/account_bank_statement_import_ofx/tests/test_import_bank_statement.py", line 23, in test_ofx_file_import

2016-10-20 10:14:09,659 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `     bank_statement.import_file()

2016-10-20 10:14:09,659 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `   File "/home/travis/odoo-8.0/openerp/api.py", line 266, in wrapper

2016-10-20 10:14:09,659 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `     return new_api(self, _args, *_kwargs)

2016-10-20 10:14:09,659 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `   File "/home/travis/build/NL66278/bank-statement-import/account_bank_statement_import/models/account_bank_statement_import.py", line 68, in import_file

2016-10-20 10:14:09,659 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `     )._import_file(data_file)

2016-10-20 10:14:09,660 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `   File "/home/travis/odoo-8.0/openerp/api.py", line 266, in wrapper

2016-10-20 10:14:09,660 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `     return new_api(self, _args, *_kwargs)

2016-10-20 10:14:09,660 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `   File "/home/travis/build/NL66278/bank-statement-import/account_bank_statement_import/models/account_bank_statement_import.py", line 122, in _import_file

2016-10-20 10:14:09,660 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `     statements = self._parse_all_files(data_file)

2016-10-20 10:14:09,660 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `   File "/home/travis/odoo-8.0/openerp/api.py", line 266, in wrapper

2016-10-20 10:14:09,660 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `     return new_api(self, _args, *_kwargs)

2016-10-20 10:14:09,660 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `   File "/home/travis/build/NL66278/bank-statement-import/account_bank_statement_import/models/account_bank_statement_import.py", line 104, in _parse_all_files

2016-10-20 10:14:09,661 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `     parse_result = self._parse_file(import_file)

2016-10-20 10:14:09,661 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `   File "/home/travis/odoo-8.0/openerp/api.py", line 266, in wrapper

2016-10-20 10:14:09,661 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `     return new_api(self, _args, *_kwargs)

2016-10-20 10:14:09,661 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `   File "/home/travis/build/NL66278/bank-statement-import/account_bank_statement_import_ofx/account_bank_statement_import_ofx.py", line 89, in _parse_file

2016-10-20 10:14:09,661 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: `     'balance_start': ofx.account.statement.balance,

2016-10-20 10:14:09,661 7004 ERROR openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: ` AttributeError: 'Statement' object has no attribute 'balance'

2016-10-20 10:14:09,661 7004 INFO openerp_test openerp.addons.account_bank_statement_import_ofx.tests.test_import_bank_statement: Ran 1 test in 0.034s

**Comment by StefanRijnhart** [comment]
This is fixed in the PR for 10.0 by https://github.com/OCA/bank-statement-import/pull/80/commits/ac4b04ef3b51a0ef812426835b25048d2320667b, but @pedrobaeza has doubts about the reliability of the change. Maybe you can give a second opinion about that

-- edit: rephrased this comment to better reflect the immense respect I have for @pedrobaeza --

**Comment by pedrobaeza** [comment]
Hehe, no problem with the original text. No offense. And I'm no more blocking it due to your arguments, so I close the issue.

**Comment by StefanRijnhart** [comment]
@pedrobaeza :ok_hand:

**Comment by NL66278** [comment]
Thanks a lot @pedrobaeza and @StefanRijnhart !!
